#!/bin/bash

process_pt_matrix="true"
process_side_effect="true"

cd pestrie_exp

for folder in *
do
    if [ "$folder" == "." ]; then
        continue
    fi
    
    if [ "$folder" == ".." ]; then
        continue
    fi

    if [ -d "$folder" ]; then
        cd $folder
	
	# points-to
	if [ "$process_pt_matrix" == "true" ]; then
	    for file in p1_o1 objsens-bdd-hs p0_o0-flowsens
	    do
		ptm_file=${file}.ptm
		
		if [ -f $ptm_file ]; then
		    bunzip2 ${ptm_file}
		fi		    
	    done
	fi

	#side-effect
	if [ "$process_side_effect" == "true" ]; then
	    for file in geomModRef flowModRef paddleModRef-hs
	    do
		    se_file=${file}.txt
		    		    
		    if [ -f $se_file ]; then
			bunzip2 ${se_file}
		    fi
	    done
	fi

	cd ..
    fi
done
